version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: poc-elasticsearch
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

    volumes:
      - elastic-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    depends_on:
      - elasticsearch
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"

    volumes:
      - kibanadata:/usr/share/kibana/data


volumes:
  elastic-data:
    driver: local
  kibanadata:
    driver: local


